version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - techdome-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://techdome_user:techdome_password@postgres:5432/techdome_db
      - PORT=5000
      - HOST=0.0.0.0
    networks:
      - techdome-network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=techdome_db
      - POSTGRES_USER=techdome_user
      - POSTGRES_PASSWORD=techdome_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - techdome-network

networks:
  techdome-network:
    driver: bridge

volumes:
  postgres-data:
